apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bluebank

resources:
- ../../base

patches:
- path: gpu-patch.yaml

replicas:
- name: vllm-coding
  count: 2

# Made with Bob
